title: "Azer Ko&#231;ulu"
url: http://azer.kodfabrik.com

author_name: Azer Koculu
author_email: azer@kodfabrik.com
twitter_id: 4zjs # http://idfromuser.com
twitter_username: 4zjs
delicious: xingjiangao
pinboard: azer
flickr_id: 98269877@N00
flickr_username: azer
github: azer
lastfm: azerkoculu
instagram: combataircraft
vimeo: azer
disqus: kodfabrikdev # shortname for comments

permalink: /:year/:month/:day/:title.html
auto: false
