title: Azer's Social Network Activities
url: http://azer.kodfabrik.com

author_name: Azer Koculu
author_email: azer@kodfabrik.com
twitter_id: 173529817 # http://idfromuser.com
twitter_username: 4zjs
delicious: xingjiangao
flickr_id: 98269877@N00
flickr_username: azer
github: azer
lastfm: azerkoculu
vimeo: azer
disqus: kodfabrikdev # shortname for comments

permalink: /:year/:month/:day/:title.html
auto: false
